print("Angel Mae Garcia")
print("Nangka, Torrijos, Marinduque")
print("May 13, 2002")
print("Mariduque State College")
print("BSI/T")
print("2D")
print("Hobbies:")
print("        Eating")
print("        Reading")
print("        Watching")
print("        Sleeping")
print("        Writing")